backend:
  replicaCount: 1
  image:
    repository: "jrochadev/backend"
    tag: "1.0"
    pullSecret: ""
  database:
    SPRING_DB_HOST: ""
    SPRING_DB_PORT: ""
    SPRING_DB_NAME: ""
    SPRING_DB_USER: ""
    SPRING_DB_PASSWORD: ""
  
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
  probes:
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3
frontend:
  replicaCount: 2
  image:
    repository: "jrochadev/mi-nginx-vue-app"
    tag: "latest"
    pullSecret: ""
  acr:
    dockerconfigjson: ""
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
  probes:
    readinessProbe:
      httpGet:
        path: /healthz                                                   
        port: 80                                                  
      initialDelaySeconds: 10                                                                 
      periodSeconds: 5                                  
      timeoutSeconds: 2                                        
      failureThreshold: 3

  
