# templates/ingress.yaml

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-frontend-ingress"
  labels:
    app: "{{ .Release.Name }}-frontend-app"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: "frontend-frontend-service"
                port:
                  number: 80
          {{- end }}
{{- end }}
