apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frontend-app"
  namespace: {{ .Release.Namespace }}  
  # HAY QUE PONER AQUI EL ANOTATIONS QUE SE CREA POR DEFECTO Y DARLE UN NOMBE APARTE DE EL QUE DA POR DEFECTO, COGE EL NOMBRE DE LA RELEASE, HAY QUE PONERSELE OTRA VEZ POR EJEMPLO PARA QUE NO SE SOLAPE
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-frontend-app"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-frontend-app"
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
      - name: "{{ .Release.Name }}-frontend-app"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.readinessProbe.failureThreshold }}
        volumeMounts:
        - name: tls-secret-volume
          mountPath: /etc/ssl/certs
          readOnly: true  
      volumes:  # Este bloque debe estar a nivel del spec, fuera de los containers
      - name: tls-secret-volume
        secret:
          secretName: tls-secret
