apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deploy
  namespace: {{ .Release.Namespace }}  
spec:
  replicas: {{ .Values.frontend.replicaCount }} 
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend-deploy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend-deploy
    spec:
      containers:
      - name: frontend-app
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: {{ .Values.frontend.probes.readinessProbe.httpGet.path }}
            port: {{ .Values.frontend.probes.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.frontend.probes.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.probes.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.frontend.probes.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.frontend.probes.readinessProbe.failureThreshold }}
#      imagePullSecrets:  # Configuración de pullSecret si está definido
#        - name: {{ .Values.frontend.image.pullSecret | quote }}
