                                                                                         
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frontend-app"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-frontend-app"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-frontend-app"
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
      - name: "{{ .Release.Name }}-frontend-app"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.readinessProbe.failureThreshold }}
        volumeMounts:
          - name: tls-secret-volume
            mountPath: /etc/ssl/certs 
            readOnly: true  
  volumes:
  - name: tls-secret-volume
    secret:
      secretName: tls-secret  

