apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend-app
    spec:
      imagePullSecrets:    
        - name: {{ .Values.image.pullSecret }}
      containers:
      env:
          - name: SPRING_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-backend-config
                key: SPRING_DB_HOST
          - name: SPRING_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-backend-config
                key: SPRING_DB_PORT
          - name: SPRING_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-backend-config
                key: SPRING_DB_NAME
          - name: SPRING_DB_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-backend-config
                key: SPRING_DB_USER
          - name: SPRING_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-backend-config
                key: SPRING_DB_PASSWORD
        ports:
          - containerPort: 8080  # Puerto que escucha tu backend
      # imagePullSecrets:
      #  - name: acr-secret-backend