apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.nameOverride }}-{{ .Release.Name }}-backend-service"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: "{{ .Values.nameOverride }}{{ .Release.Name }}-backend-app"  
  ports:
    - protocol: TCP
      port: 8080   
      targetPort: 8080  
  type: ClusterIP  
