apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: "{{ .Release.Name }}-app"  
  ports:
    - protocol: TCP
      port: 8080   
      targetPort: 8080  
  type: ClusterIP  
