apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: {{ .Release.Name }}-backend-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
