apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.nameOverride }}-{{ .Release.Name }}-backend-config"
  namespace: {{ .Release.Namespace }}
data:
  SPRING_DB_HOST: "{{ .Values.database.SPRING_DB_HOST }}"
  SPRING_DB_PORT: "{{ .Values.database.SPRING_DB_PORT }}"
  SPRING_DB_NAME: "{{ .Values.database.SPRING_DB_NAME }}"
  SPRING_DB_USER: "{{ .Values.database.SPRING_DB_USER }}"
  SPRING_DB_PASSWORD: "{{ .Values.database.SPRING_DB_PASSWORD }}"
