---
- name: Backup de base de datos PostgreSQL
  hosts: database_server
  become: yes
  vars:
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    backup_dir: "{{ lookup('env', 'BACKUP_DIR') }}"
    backup_filename: "{{ db_name }}_{{ ansible_date_time.iso8601 }}.sql"
  
  tasks:
    - name: Crear el directorio de backup si no existe
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'
        owner: db_user
        group: db_user
      become: yes
    
    - name: Realizar backup de la base de datos PostgreSQL
      shell: >
        pg_dump -h 127.0.0.1 -U myuser {{ db_name }}
        > {{ backup_dir }}/{{ backup_filename }}
      become: no
      environment:
        PGUSER: db_user
        PGPASSWORD: db_password
    
    - name: Comprimir el archivo de respaldo
      command: gzip "{{ backup_dir }}/{{ backup_filename }}"
      args:
        removes: "{{ backup_dir }}/{{ backup_filename }}"
