---
- name: Backup de base de datos PostgreSQL
  hosts: database_server
  become: yes
  vars:
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    backup_dir: "{{ lookup('env', 'BACKUP_DIR') }}"
    backup_filename: "{{ db_name }}_{{ ansible_date_time.iso8601 }}.sql"
  tasks:
 
    - name: Realizar el backup de la base de datos
      shell: >
        pg_dump -U {{ db_user}} {{ db_name }} -h 10.0.1.4  > /tmp/{{ db_name }}_{{ ansible_date_time.date }}.sql
      become_user: postgres
 
    - name: Confirmar que el archivo de backup se creó
      stat:
        path: "/tmp/{{ db_name }}_{{ ansible_date_time.date }}.sql"
      register: backup_status
 
    - name: Mostrar resultado del backup
      debug:
        msg: >
          El backup se ha creado correctamente en
          /tmp/{{ db_name }}_{{ ansible_date_time.date }}.sql
      when: backup_status.stat.exists

 
