- hosts: database_server
  become: yes
  vars:
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: md5 }
      - { type: local, database: all, user: all, auth_method: md5 }
      - { type: host, database: all, user: myuser, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: myuser, address: '::1/128', auth_method: md5 }
      - { type: host, database: orquestas, user: myuser, address: '192.168.1.0/24', auth_method: md5 }
      - { type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5 }
    postgresql_version: "14"

  roles:
    - role: geerlingguy.postgresql
      postgresql_databases:
        - name: orquestas
          state: present

      postgresql_users:
        - name: myuser
          password: mypassword
          encrypted: yes
          state: present

  tasks:
    - name: Agregar listen_addresses al archivo de configuración con echo
      ansible.builtin.shell: |
        echo "listen_addresses = '*'" >> /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
      become: yes
      args:
        creates: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
      notify: restart postgresql

  handlers:
    - name: restart postgresql
      ansible.builtin.service:
        name: postgresql
        state: restarted
