- name: Instalar y configurar PostgreSQL
  hosts: "10.0.1.4"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    postgres_version: "14"  # Versión de PostgreSQL que deseas instalar
  tasks:
    - name: Añadir el repositorio de PostgreSQL
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -c | awk '{print $2}')-pgdg main"
        state: present
        filename: "pgdg"
        update_cache: yes

    - name: Instalar los paquetes necesarios de PostgreSQL
      apt:
        name:
          - "postgresql-{{ postgres_version }}"
          - "postgresql-contrib-{{ postgres_version }}"
          - "python3-psycopg2"
        state: present
        update_cache: yes

    - name: Asegurarse de que el servicio PostgreSQL está activo
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Crear la base de datos
      become_user: postgres
      postgresql_db:
        name: orquestas
        state: present

    - name: Crear el usuario de base de datos
      become_user: postgres
      postgresql_user:
        name: ""
        password: ""
        encrypted: yes
        state: present

    - name: Asignar privilegios al usuario en la base de datos
      become_user: postgres
      postgresql_privs:
        db: ""
        objs: ALL_IN_SCHEMA
        privs: ALL
        type: table
        role: myuser
