---
- name: Configuraci칩n de PostgreSQL
  hosts: all
  become: true
 
  vars:
    postgres_user: myuser
    postgres_db: orquestas
    # postgres_password: password
 
  tasks:
    - name: Actualizar el repositorio de paquetes
      apt:
        update_cache: yes
 
    - name: Instalar PosgreSQL y los paquetes necesarios
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present
        update_cache: yes
 
    - name: Asegurarse de que PostgreSQL est치 en ejecuci칩n
      service:
        name: postgresql
        state: started
        enabled: true
 
    - name: Crear una base de datos
      become: true
      become_user: postgres
      postgresql_db:
        name: "{{ postgres_db }}"
        owner: "postgres"
        encoding: "UTF8"
        state: present
 
    - name: Crear usuario PostgreSQL
      become: true
      become_user: postgres
      postgresql_user:
        name: "{{ postgres_user }}"
        # password: "{{ postgres_password }}"
        role_attr_flags: SUPERUSER
        state: present
 
    - name: Cambiar el propietario de la base de datos
      become: true
      become_user: postgres
      shell: |
        psql -c "ALTER DATABASE {{ postgres_db }} OWNER TO {{ postgres_user }};"
 
    # - name: Configurar la contrase침a del usuario PostgreSQL
    #   become: true
    #   become_user: postgres
    #   shell: |
    #     psql -c "ALTER USER {{ postgres_user }} WITH PASSWORD '{{ postgres_password }}';"
