- hosts: database_server
  become: yes
  vars:
    postgresql_version: "14" 
  roles:
    - role: geerlingguy.postgresql
      postgresql_databases:
        - name: orquestas  
          state: present  
      postgresql_users:
        - name: myuser 
          password: mypassword  
          encrypted: yes  
          state: present  
