
- hosts: database_server
  become: yes
  vars:
    # Configuraci칩n para PostgreSQL
    postgresql_version: "12"  # O la versi칩n que necesites
    postgresql_databases:
      - name: orquestas  # Nombre de la base de datos que deseas crear
    postgresql_users:
      - name: myuser  # Nombre del usuario
        password: "mypassword"  # Contrase침a del usuario
        priv: "ALL"  # Privilegios sobre la base de datos
        db: orquestas  # Base de datos a la que tendr치 acceso

  roles:
    - geerlingguy.postgresql

