- name: Instalar y configurar PostgreSQL
  hosts: "10.0.1.4"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Instalar los paquetes necesarios
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present
        update_cache: yes
 
    - name: Asegurarse de que el servicio PostgreSQL está activo
      service:
        name: postgresql
        state: started
        enabled: yes
 
    - name: Crear la base de datos
      become_user: postgres
      postgresql_db:
        name: orquestas
        state: present
 
    - name: Crear el usuario de base de datos
      become_user: postgres
      postgresql_user:
        name: ""
        password: ""
        encrypted: yes
        state: present
 
    - name: Asignar privilegios al usuario en la base de datos
      become_user: postgres
      postgresql_privs:
        db: ""
        objs: ALL_IN_SCHEMA
        privs: ALL
        type: table
        role: myuser