- hosts: database_server
  become: yes
  vars:
    postgres_user: "postgres"
    postgres_db: "{{ lookup('env', 'DB_NAME') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    encryption_key: "{{ lookup('env', 'ENCRYPTION_KEY') }}"

    local_backup_dir: "/var/backups/"
    
    azure_client_id: "{{ lookup('env', 'ARM_CLIENT_ID') }}"
    postgresql_hba_entries:
      - { type: local, database: all, user: "{{ postgres_user }}", auth_method: md5 }
      - { type: local, database: all, user: all, auth_method: md5 }
      - { type: host, database: all, user: "{{ db_user }}", address: "127.0.0.1/32", auth_method: md5 }
      - { type: host, database: all, user: "{{ db_user }}", address: "::1/128", auth_method: md5 }
      - { type: host, database: "{{ postgres_db }}", user: "{{ db_user }}", address: "192.168.1.0/24", auth_method: md5 }
      - { type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5 }
    postgresql_version: "14"
    postgresql_global_config_options:
      - option: listen_addresses
        value: '*'
      - option: log_directory
        value: '/var/log/postgresql'


  roles:
    - role: geerlingguy.postgresql
      postgresql_databases:
        - name: {{ postgres_db }}
          state: present

      postgresql_users:
        - name: {{ db_user }}
          password: {{ db_password }}
          encrypted: yes
          state: present

  # tasks:
  #   - name: Agregar listen_addresses al archivo de configuración con echo
  #     ansible.builtin.shell: |
  #       echo "listen_addresses = '*'" >> /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
  #     become: yes 
  #     args:
  #       creates: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
  #     notify: restart postgresql

  # handlers:
  #   - name: restart postgresql
  #     ansible.builtin.service:
  #       name: postgresql
  #       state: restarted
  #     become: yes
