- hosts: database_sever
  become: yes
  vars:
    # Configuración para PostgreSQL
    postgresql_version: "14" 
    postgresql_databases:
      - name: orquestas 
    postgresql_users:
      - name: myuser
        password: "mypassword"
        priv: "SELECT, INSERT, UPDATE, DELETE"
        db: orquestas


  roles:
    - geerlingguy.postgresql
