# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
backend:
  
  replicaCount: 1
  image:
    repository: "jrochadev/backend"
    tag: "1.0"
    pullSecret: ""
  database:
    SPRING_DB_HOST: "postgres-service"
    SPRING_DB_PORT: "5432"
    SPRING_DB_NAME: "orquestas"
    SPRING_DB_USER: "myuser"
    SPRING_DB_PASSWORD: "mypassword"
  
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
  probes:
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3
