name: Ansible
 
on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read
 
jobs:
  ansible:
    name: Ansible Workflow
    runs-on: self-hosted
 
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      PUBLIC_IP: ${{ vars.PUBLIC_IP }}
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Ansible and sshpass
        run: |
          sudo apt update -y
          sudo apt install ansible -y
          sudo apt install sshpass -y
          
      - name: Create inventory.ini file
        run: |
          echo "[database_server]" > inventory.ini
          echo "10.0.1.4 ansible_user=${{ secrets.VM_BD_USER }} ansible_password=${{ secrets.VM_BD_PASS }}" >> inventory.ini
        working-directory: ./ansible
      - name: Execute playbook
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.ini up.yaml
        working-directory: ./ansible

      
     
