name: Empaquetar y subir el chart a Harbor

on:
  workflow_dispatch:
    inputs:
      chart_name:
        description: 'Selecciona el nombre del Helm Chart a subir'
        required: true
        type: choice
        options:
          - backend
          - frontend

jobs:
  package-and-push:
    # runs-on: runner-stemdo-labs
    runs-on: ubuntu-latest
    env:
     ARC_NAME: ${{ secrets.ACR_NAME }}
     ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
     ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
     ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}


    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use custom action to package and push Helm chart
      uses: ./.github/actions/upload_helm
      with:
        chart_name: ${{ inputs.chart_name }}
        chart_directory: './charts'
        harbor_username: ${{ secrets.HARBOR_USER }}
        harbor_password: ${{ secrets.HARBOR_PASS }}
        harbor_ip: ${{ secrets.HARBOR_IP }}
        acr_name: ${{ secrets.ACR_NAME }}
        arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
        arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
        arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
        arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    # - name: Commit and Push Changes
    #   uses: EndBug/add-and-commit@v9
    #   with:
    #     add: '.'
    #     author_name: "github-actions[bot]"
    #     author_email: "github-actions[bot]@users.noreply.github.com"
    #     commit: '--signoff'
    #     message: "Update version"
    #     push: true
    #     pathspec_error_handling: 'exitImmediately'
    #     cwd: '.'  
