name: Empaquetar y subir el chart a Harbor

on:
  workflow_dispatch:
    inputs:
      chart_name:
        description: 'Nombre del Helm Chart a subir'
        required: true
        type: string

jobs:
  package-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use custom action to package and push Helm chart
      uses: ./path/to/your/action
      with:
        chart_name: ${{ inputs.chart_name }}
        chart_directory: './charts'
        harbor_username: ${{ secrets.HARBOR_USERNAME }}
        harbor_password: ${{ secrets.HARBOR_PASSWORD }}
        harbor_ip: ${{ secrets.HARBOR_IP }}
